import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const read=p=>fs.readFileSync(path.join(root,p),'utf8');const exists=p=>fs.existsSync(path.join(root,p));const require=createRequire(import.meta.url);
const required=['standards/re-entry.html','standards/re-entry-handoff.html','assets/reentry.css','assets/reentry-config.js','assets/reentry.js','assets/reentry-handoff.js','assets/reentry-etsy-insert.svg','api/reentry-pilot.js','.env.example'];required.forEach(p=>assert.ok(exists(p),`Missing ${p}`));
const catalog=read('standards/index.html');assert.match(catalog,/LIVE SYSTEMS/);assert.match(catalog,/Aftercare that changes with recovery/);assert.match(catalog,/\/standards\/re-entry\.html/);assert.match(catalog,/DOWNLOADABLE STANDARDS/);assert.match(catalog,/microneedling-pre-care\.html/);assert.match(catalog,/summer-skin-safety\.html/);
const sales=read('standards/re-entry.html');assert.match(sales,/Stop answering/);assert.match(sales,/Can I use this yet/);assert.match(sales,/https:\/\/re-entry-eight\.vercel\.app\/client\/SP-0042\/demo-secure-token/);assert.match(sales,/id="founding-pilot"/);assert.match(sales,/Do not include client names, symptoms, treatment records/);assert.match(sales,/I understand this is a founding pilot inquiry/);assert.match(sales,/not an immediate software purchase/i);assert.match(sales,/rel="noopener noreferrer external"/);assert.match(sales,/canonical/);assert.match(sales,/application\/ld\+json/);
const simulator=read('standards/re-entry-handoff.html');assert.match(simulator,/AFTERCARE HANDOFF SIMULATOR/);assert.match(simulator,/What happens after the handout leaves your hands/);assert.doesNotMatch(simulator,/\bpercent(age)?\b|\bgrade\b|\bmaturity level\b|\bclinical-risk\b/i);assert.match(simulator,/not stored, transmitted, or added to analytics/i);
const sandbox={window:{location:{href:'https://example.test/standards/re-entry.html'}},URL,Object};vm.createContext(sandbox);vm.runInContext(read('assets/products.js'),sandbox);const commerce=sandbox.window.UndoneCommerce;const reentry=commerce.getProduct('re-entry');assert.equal(reentry.productType,'live-system');assert.equal(reentry.status,'founding-pilot');assert.equal(reentry.checkoutUrl,null);assert.equal(commerce.buildOutboundUrl({productId:'re-entry'}),null);assert.equal(reentry.demoUrl,'https://re-entry-eight.vercel.app/client/SP-0042/demo-secure-token');assert.equal(reentry.pilotUrl,'/standards/re-entry.html#founding-pilot');
const micro=read('standards/microneedling-pre-care.html');const bridge='/standards/re-entry.html?utm_source=undone_tools&amp;utm_medium=product_cross_sell&amp;utm_campaign=reentry_pilot&amp;utm_content=microneedling_precare';assert.ok(micro.includes(bridge),'Microneedling bridge URL is incorrect');assert.match(micro,/data-buy data-product="microneedling-pre-care"/);assert.match(micro,/data-cta-location="sticky"/);
const qr=read('assets/reentry-etsy-insert.svg');assert.match(qr,/YOUR AFTERCARE HANDOUT/);assert.match(qr,/CAN BECOME A LIVE SKIN PASS/);assert.match(qr,/undone\.tools\/standards\/re-entry/);assert.match(qr,/<path|<rect/);
const handoff=require(path.join(root,'assets/reentry-handoff.js'));assert.deepEqual(handoff.evaluateHandoff({delivery:'pdf',change:'replacement',today:'sometimes',unknown:'asks-us',access:'no'}),{issued:'present',availableToday:'manual',nextChange:'manual',unknownQuestion:'manual',providerUpdate:'manual',accessControl:'missing'});assert.deepEqual(handoff.evaluateHandoff({delivery:'patient-portal',change:'yes',today:'yes',unknown:'asks-us',access:'yes'}),{issued:'present',availableToday:'present',nextChange:'manual',unknownQuestion:'manual',providerUpdate:'present',accessControl:'present'});
const reentryJs=read('assets/reentry.js');for(const event of ['reentry_page_viewed','reentry_demo_clicked','reentry_pilot_cta_clicked','reentry_pilot_form_started','reentry_pilot_form_submitted','reentry_pilot_form_failed','reentry_etsy_bridge_clicked'])assert.match(reentryJs,new RegExp(event));const handoffJs=read('assets/reentry-handoff.js');assert.match(handoffJs,/reentry_simulator_started/);assert.match(handoffJs,/reentry_simulator_completed/);assert.doesNotMatch(handoffJs,/localStorage|sessionStorage|fetch\(/);assert.doesNotMatch(handoffJs,/answers\s*:/);assert.match(reentryJs,/ALLOWED_ANALYTICS_KEYS/);assert.doesNotMatch(reentryJs,/email:\s*payload|businessName:\s*payload|repeatedQuestion:\s*payload/);
const config=require(path.join(root,'assets/reentry-config.js'));assert.equal(config.contactEmail,'hello@undone.design');const pilotSource=read('api/reentry-pilot.js');assert.doesNotMatch(pilotSource,/console\.(log|info|warn|error)/);for(const token of ['service_not_configured','unsupported_media_type','body_too_large','rate_limited','faxNumber','REENTRY_PILOT_INBOX','RESEND_API_KEY','REENTRY_PILOT_FROM'])assert.match(pilotSource,new RegExp(token));
const handler=require(path.join(root,'api/reentry-pilot.js'));function mock(){return{headers:{},statusCode:200,body:null,setHeader(n,v){this.headers[n]=v},status(c){this.statusCode=c;return this},json(b){this.body=b;return this}}}{const response=mock();await handler({method:'GET',headers:{},socket:{}},response);assert.equal(response.statusCode,405);assert.equal(response.body.code,'method_not_allowed')}{const response=mock();await handler({method:'POST',headers:{'content-type':'text/plain'},body:{},socket:{}},response);assert.equal(response.statusCode,415)}{const old=[process.env.REENTRY_PILOT_INBOX,process.env.RESEND_API_KEY,process.env.REENTRY_PILOT_FROM];delete process.env.REENTRY_PILOT_INBOX;delete process.env.RESEND_API_KEY;delete process.env.REENTRY_PILOT_FROM;const response=mock();await handler({method:'POST',headers:{'content-type':'application/json','x-forwarded-for':'198.51.100.1'},body:{},socket:{}},response);assert.equal(response.statusCode,503);assert.equal(response.body.code,'service_not_configured');assert.equal(response.body.fallbackEmail,'hello@undone.design');if(old[0])process.env.REENTRY_PILOT_INBOX=old[0];if(old[1])process.env.RESEND_API_KEY=old[1];if(old[2])process.env.REENTRY_PILOT_FROM=old[2]}
for(const folder of ['vault','chaos-vault']){if(!exists(folder))continue;const stack=[path.join(root,folder)];while(stack.length){const current=stack.pop();fs.readdirSync(current,{withFileTypes:true}).forEach(entry=>{const next=path.join(current,entry.name);if(entry.isDirectory())stack.push(next);if(!entry.isFile()||!/\.(html|js)$/.test(entry.name))return;const source=fs.readFileSync(next,'utf8');assert.doesNotMatch(source,/data-reentry-(demo|pilot|etsy-bridge)|reentry_pilot_form|\/api\/reentry-pilot/,`${next} must remain isolated from RE:ENTRY commerce`)})}}
const targets=new Set();for(const htmlPath of ['standards/re-entry.html','standards/re-entry-handoff.html','standards/microneedling-pre-care.html']){const html=read(htmlPath);for(const match of html.matchAll(/<a\b[^>]*href="(\/[^"#?]+(?:\.html|\/))[^\"]*"/g))targets.add(match[1])}for(const target of targets){if(target==='/')continue;const relative=target.endsWith('/')?`${target.slice(1)}index.html`:target.slice(1);assert.ok(exists(relative),`Broken internal target ${target}`)}console.log('RE:ENTRY sales funnel validation passed.');
