const { contactEmail } = require('../assets/reentry-config.js');

const MAX_BODY_BYTES = 12_000;
const WINDOW_MS = 10 * 60 * 1000;
const MAX_ATTEMPTS = 5;
const ALLOWED_KEYS = new Set(['name','businessName','email','socialUrl','primaryTreatment','appointmentsPerMonth','aftercareMethod','repeatedQuestion','faxNumber','consent']);
const APPOINTMENT_RANGES = new Set(['1-10','11-25','26-50','51-100','100+']);
const DELIVERY_METHODS = new Set(['printed-handout','pdf','text-message','verbal','patient-portal','mixed']);
const attempts = new Map();

function sendJson(response,status,body){response.setHeader('Cache-Control','no-store');response.setHeader('Content-Type','application/json; charset=utf-8');response.setHeader('Content-Security-Policy',"default-src 'none'; frame-ancestors 'none'");response.setHeader('X-Content-Type-Options','nosniff');response.setHeader('Referrer-Policy','no-referrer');return response.status(status).json(body)}
function parseBody(request){if(request.body===null||request.body===undefined)throw new TypeError('request body is required');const body=typeof request.body==='string'?JSON.parse(request.body):request.body;if(!body||typeof body!=='object'||Array.isArray(body))throw new TypeError('request body must be a JSON object');const serialized=JSON.stringify(body);if(Buffer.byteLength(serialized,'utf8')>MAX_BODY_BYTES){const error=new RangeError('request body is too large');error.code='body_too_large';throw error}const unexpectedKeys=Object.keys(body).filter(key=>!ALLOWED_KEYS.has(key));if(unexpectedKeys.length>0)throw new TypeError('request body contains unsupported fields');return body}
function cleanString(value,field,max,options={}){const required=options.required===true;const text=typeof value==='string'?value.trim():'';if(required&&!text)throw new TypeError(`${field} is required`);if(text.length>max)throw new RangeError(`${field} is too long`);return text}
function validatePayload(body){const payload={name:cleanString(body.name,'name',80,{required:true}),businessName:cleanString(body.businessName,'businessName',120,{required:true}),email:cleanString(body.email,'email',160,{required:true}).toLowerCase(),socialUrl:cleanString(body.socialUrl,'socialUrl',240),primaryTreatment:cleanString(body.primaryTreatment,'primaryTreatment',100,{required:true}),appointmentsPerMonth:cleanString(body.appointmentsPerMonth,'appointmentsPerMonth',20,{required:true}),aftercareMethod:cleanString(body.aftercareMethod,'aftercareMethod',40,{required:true}),repeatedQuestion:cleanString(body.repeatedQuestion,'repeatedQuestion',500),faxNumber:cleanString(body.faxNumber,'faxNumber',100),consent:cleanString(body.consent,'consent',20,{required:true})};if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(payload.email))throw new TypeError('email is invalid');if(payload.socialUrl){let parsed;try{parsed=new URL(payload.socialUrl)}catch(_){throw new TypeError('socialUrl is invalid')}if(!['http:','https:'].includes(parsed.protocol))throw new TypeError('socialUrl must use http or https')}if(!APPOINTMENT_RANGES.has(payload.appointmentsPerMonth))throw new TypeError('appointmentsPerMonth is invalid');if(!DELIVERY_METHODS.has(payload.aftercareMethod))throw new TypeError('aftercareMethod is invalid');if(payload.consent!=='accepted')throw new TypeError('consent is required');return payload}
function requestKey(request){const forwarded=String(request.headers&&request.headers['x-forwarded-for']||'');const first=forwarded.split(',')[0].trim();return first||String(request.socket&&request.socket.remoteAddress||'unknown')}
function isRateLimited(request){const key=requestKey(request);const now=Date.now();const current=attempts.get(key);if(!current||now-current.startedAt>=WINDOW_MS){attempts.set(key,{count:1,startedAt:now});return false}current.count+=1;attempts.set(key,current);return current.count>MAX_ATTEMPTS}
function escapeHtml(value){return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function buildEmail(payload){const repeatedQuestion=payload.repeatedQuestion?`<p><strong>Repeated question:</strong><br>${escapeHtml(payload.repeatedQuestion)}</p>`:'<p><strong>Repeated question:</strong> Not provided</p>';return{subject:`RE:ENTRY founding pilot inquiry · ${payload.businessName}`,html:['<h1>RE:ENTRY founding pilot inquiry</h1>',`<p><strong>Name:</strong> ${escapeHtml(payload.name)}</p>`,`<p><strong>Business:</strong> ${escapeHtml(payload.businessName)}</p>`,`<p><strong>Email:</strong> ${escapeHtml(payload.email)}</p>`,`<p><strong>Instagram or website:</strong> ${escapeHtml(payload.socialUrl||'Not provided')}</p>`,`<p><strong>Primary treatment:</strong> ${escapeHtml(payload.primaryTreatment)}</p>`,`<p><strong>Appointments per month:</strong> ${escapeHtml(payload.appointmentsPerMonth)}</p>`,`<p><strong>Current handoff:</strong> ${escapeHtml(payload.aftercareMethod)}</p>`,repeatedQuestion,'<p>Consent confirmed: founding pilot inquiry, not an immediate purchase.</p>'].join('')}}
async function sendWithResend(payload,settings){const message=buildEmail(payload);const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${settings.apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({from:settings.from,to:[settings.inbox],reply_to:payload.email,subject:message.subject,html:message.html})});if(!response.ok){const error=new Error('email_delivery_failed');error.code='email_delivery_failed';throw error}}
async function handler(request,response){if(request.method!=='POST'){response.setHeader('Allow','POST');return sendJson(response,405,{ok:false,code:'method_not_allowed'})}const contentType=String(request.headers&&request.headers['content-type']||'');if(!contentType.toLowerCase().includes('application/json'))return sendJson(response,415,{ok:false,code:'unsupported_media_type'});if(isRateLimited(request))return sendJson(response,429,{ok:false,code:'rate_limited'});const settings={inbox:process.env.REENTRY_PILOT_INBOX,apiKey:process.env.RESEND_API_KEY,from:process.env.REENTRY_PILOT_FROM};if(!settings.inbox||!settings.apiKey||!settings.from)return sendJson(response,503,{ok:false,code:'service_not_configured',fallbackEmail:contactEmail});try{const body=parseBody(request);const payload=validatePayload(body);if(payload.faxNumber)return sendJson(response,202,{ok:true,code:'accepted'});await sendWithResend(payload,settings);return sendJson(response,202,{ok:true,code:'accepted'})}catch(error){if(error&&error.code==='body_too_large')return sendJson(response,413,{ok:false,code:'body_too_large'});if(error&&error.code==='email_delivery_failed')return sendJson(response,502,{ok:false,code:'delivery_failed',fallbackEmail:contactEmail});if(error instanceof SyntaxError||error instanceof TypeError||error instanceof RangeError)return sendJson(response,400,{ok:false,code:'invalid_request'});return sendJson(response,500,{ok:false,code:'internal_error'})}}
module.exports=handler;module.exports._test={parseBody,validatePayload,buildEmail,escapeHtml,isRateLimited,MAX_BODY_BYTES};
